# Generated by Django 3.1.3 on 2020-12-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201216_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click on blog name to read post!', max_length=255),
        ),
    ]
